CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_name VARCHAR(255) NOT NULL,
                                     user_email VARCHAR(500)

);

CREATE TABLE IF NOT EXISTS items (
                                     item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     item_name VARCHAR(255) NOT NULL,
                                     item_description VARCHAR(150) NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     request_id BIGINT,
                                     CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
                                        comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(2000) NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        author_id BIGINT NOT NULL,
                                        CONSTRAINT fk_comments_to_users FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                        CONSTRAINT fk_comments_to_items FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                                        booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        booker_id BIGINT NOT NULL,
                                        status VARCHAR (50),
                                        FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
                                        FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
                                        request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        requester_id BIGINT NOT NULL,
                                        description  VARCHAR (200) NOT NULL,
                                        request_date TIMESTAMP WITHOUT TIME ZONE,
                                        FOREIGN KEY (requester_id) REFERENCES users (user_id) ON DELETE CASCADE
);

INSERT INTO users (user_name, user_email)
VALUES ('TestUser1', 'user1@mail.ru');

INSERT INTO users (user_name, user_email)
VALUES ('TestUser2', 'user2@mail.ru');

INSERT INTO requests (requester_id, description, request_date)
VALUES ( 1, 'Test request description1', '2025-07-07T10:15:25');

INSERT INTO requests (requester_id, description, request_date)
VALUES (2, 'Test request description2', '2025-08-08T15:10:20');

INSERT INTO items (item_name, item_description, is_available, owner_id, request_id)
VALUES ('testItem1', 'test description1', 'false', 1, 2);

INSERT INTO items (item_name, item_description, is_available, owner_id, request_id)
VALUES ('testItem2', 'test description2', 'true', 2, 2);

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-07-07T14:40:35', '2025-07-25T18:12:43', 1, 1, 'WAITING');

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-08-08T15:45:30', '2025-08-18T12:10:40', 2, 2, 'APPROVED');

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-03-07T14:40:35', '2025-05-25T18:12:43', 1, 1, 'WAITING');

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-09-07T14:40:35', '2025-10-25T18:12:43', 1, 1, 'WAITING');

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-05-07T14:40:35', '2025-10-25T18:12:43', 1, 1, 'REJECTED');

INSERT INTO bookings (start_date, end_date, item_id, booker_id, status)
VALUES ('2025-02-07T14:40:35', '2025-02-25T18:12:43', 2, 1, 'APPROVED');

INSERT INTO comments (text, item_id, author_id)
VALUES ('Test comment text1', 1, 1);
